[package]
name = "gladius_slicer"
version = "0.4.1"
authors = ["mrhatman <lucasince@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[workspace]
members = [ 
    "gladius_shared"
]

[features]
json_schema_gen = ["gladius_shared/json_schema_gen"]
[lints.clippy]
allow-unwrap-in-tests = "allow"

[dependencies]
clap = { version = "4", features = ["derive"]}
simple_logger = "5.0.0"
log = "0.4.22"

nalgebra = "0.33"
itertools = "0.13"
geo = { version = "0.29", features = ["use-serde"] }
geo-clipper = "0.8.0"
geo-svg = "0.7"
geo-offset = { version = "0.3.2", git = "https://github.com/TimTheBig/geo-offset.git" }

serde = { version = "1.0", features = ["derive"] }
deser-hjson = "2.2"
serde_json = "^1.0.85"
bincode = "1.3.3"
ordered-float = "4.3"
rayon = "1.5.1"

rand = "0.8.5"

evalexpr = "12.0.1"

gladius_shared = { path = "gladius_shared", version = "0.5.0" }
