[package]
name = "gladius_slicer"
version = "0.4.1"
authors = ["mrhatman <lucasince@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[workspace]
members = [ 
    "gladius_shared"
]

[features]
# create/updates settings/schema.json
json_schema_gen = ["gladius_shared/json_schema_gen"]

[lints.clippy]
allow-unwrap-in-tests = "allow"

[dependencies]
clap = { version = "4.5", features = ["derive"]}
simple_logger = "5.0"
log = { version = "0.4", features = ["release_max_level_info"] }

itertools = "0.14"
binary-heap-plus = "0.5"

nalgebra = "0.33"
geo-3d = { version = "0.30", features = ["use-serde"], git = "https://github.com/TimTheBig/geo-3d.git" }
geo-clipper = "0.9.0"
geo-offset = { version = "0.3.2", git = "https://github.com/TimTheBig/geo-offset.git" }

serde = { version = "1.0", features = ["derive"] }
deser-hjson = "2.2"
serde_json = "^1.0.85"
bincode = { version = "2.0", features = ["serde", "std"], default-features = false }
ordered-float = "5.0"
rayon = "1.10"

rand = "0.9"

evalexpr = "12.0"
time = "0.3"

gladius_shared = { path = "gladius_shared", version = "0.5.0" }
